---
appname:
  # actions is a simple linux shell commands
  test:       'sleep 20 && echo 123'

  # allow combine actions of the same level
  up:         [pull, prepare, start]
  restart:    [stop, start]

  pull:       git pull

  prepare:    rails assets:precompile

  # if var is upcase, it will be required in API as a param
  start:      rails s -e production -p $PORT

  # if var is downcase, it will be not required, just local stuff
  stop:       f=tmp/pids/server.pid; if [ -f "$f" ]; then rm $f; fi

  # allow grouping actions in sublevels
  log:
    clean:    '>log/production.log'
    view:     cat log/production.log
